library(dplyr)
library(data.table)
clumped_snpid <- read.table("clumped_snpid",header=T)
effect <- read.table("ld_effect_allele_rmZW_ref_re900",header=T)
eqtl <- fread("eqtl_raw.dat",header=T)
gwas <- fread("gwas_input",header=T)
combine1 <- inner_join(clumped_snpid,eqtl,by="snpid")
combine2 <- inner_join(effect,combine1,by="snpid")
combine3 <- inner_join(combine2,gwas,by="snpid")
write.table(combine3,"mrjti_input_raw",row.names=FALSE)
